FROM python:3.13-slim

WORKDIR /app

COPY reqs-model.txt ./
RUN pip install --no-cache-dir -r reqs-model.txt

COPY model/ ./

EXPOSE 8081

RUN useradd -m nonroot
USER nonroot

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8081"]
