FROM python:3.13-slim

WORKDIR /app

COPY reqs-frontend.txt ./
RUN pip install --no-cache-dir -r reqs-frontend.txt

COPY frontend/ ./

ENV STREAMLIT_SERVER_HEADLESS=true
EXPOSE 8501

RUN useradd -m nonroot
USER nonroot

CMD ["streamlit", "run", "app.py"]
