
x-common: &common
  networks:
    - titanic

services:

  frontend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    environment:
      backend_url: http://backend:8080
    <<: *common

  backend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: host.docker.internal
      DB_USER: root
      DB_PORT: "3306"
      DB_PASSWORD: rootpassword
      DB_NAME: titanic_db
    depends_on:
      - database
    <<: *common

  model:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.model
    ports:
      - "8081:8081"
    <<: *common

  database:
    image: mysql:9.2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: titanic_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # create db & table
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    <<: *common

volumes:
  mysql_data:
    driver: local

networks:
  titanic:
    name: titanic

