FROM python:3.13-slim

WORKDIR /app

COPY reqs-backend.txt ./
RUN pip install --no-cache-dir -r reqs-backend.txt

COPY backend/ ./

EXPOSE 8080

RUN useradd -m nonroot
USER nonroot

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]
